export const data = [
  {
    header: "Supervisor",
    desc: "Monitors activity to identify project roadblocks",
    icon: "icon-supervisor.svg",
    color: "#44d3d2",
    animation: "right",
    grid: "left",
    self: "center",
  },
  {
    header: "Team Builder",
    desc: "Scans our talent network to create the optimal team for your project",
    icon: "icon-team-builder.svg",
    color: "#ea5454",
    animation: "down",
    grid: "top",
    self: "auto",
  },
  {
    header: "Karma",
    desc: "Regularly evaluates our talent to ensure quality",
    icon: "icon-karma.svg",
    color: "#fcae4a",
    animation: "up",
    grid: "down",
    self: "auto",
  },
  {
    header: "Calculator",
    desc: "Uses data from past projects to provide better delivery estimates",
    icon: "icon-calculator.svg",
    color: "#549ef2",
    animation: "left",
    grid: "right",
    self: "center",
  },
];
